<!--
```{article-info}
\:author: basics
\:date: "{sub-ref}`today`"
\:read-time: "{sub-ref}`wordcount-minutes` min read"
```
-->

(classical-electromagnetism:media)=
# Electromagnetism in Matter

**todo**

## Vacuum

Electromagnetic phenomena in a vacuum are governed by Maxwell's equations in a vacuum,

$$\begin{cases}
\nabla \cdot \mathbf{e} = \frac{\rho}{\varepsilon_0} \\
\nabla \times \mathbf{e} + \partial_t \mathbf{b} = \mathbf{0} \\
\nabla \cdot \mathbf{b} = 0 \\
\nabla \times \mathbf{b} - \mu_0 \varepsilon_0 \partial_t \mathbf{e} = \mu_0 \mathbf{j}
\end{cases}$$

and by the continuity equation of electric charge,

$$\partial_t \rho + \nabla \cdot \mathbf{j} = 0 \ .$$

## Continuous Media

In general, some materials respond to an imposed "external" electromagnetic field with polarization and magnetization. In particular, the electric polarization of a material corresponds to a local separation of electric charges, macroscopically equivalent to a volume density of dipoles, $\mathbf{p}(\mathbf{r}_0)$; magnetization corresponds to an orientation of the axes of Amperian current loops, macroscopically equivalent to a density of magnetic moment $\mathbf{m}(\mathbf{r}_0)$.

## Polarization

### Single Electric Dipole
A discrete electric dipole is formed by two equal and opposite electric charges $q$, $-q$, at points $P_+$, $P_- = P_+ \mathbf{l}$, in the limit $q \rightarrow +\infty$, $|\mathbf{l}| \rightarrow 0$ with $q |\mathbf{l}|$ finite.

The electric field (stationary **todo** *check what happens in the non-stationary case. Perhaps after deriving the general solution to the problem, as a solution to the wave equations in terms of EM potentials*) generated at the point in space $\mathbf{r}$ by an electric dipole at the point $\mathbf{r}_0$ is calculated as the limit of the electric field generated by two equal and opposite charges $q^{\mp}$ at the points $\mathbf{r}_0 \mp \frac{\mathbf{l}}{2}$,

$$\mathbf{e}(\mathbf{r}) = -\frac{q}{4 \pi \varepsilon_0} \frac{\mathbf{r} - \left( \mathbf{r}_0 - \frac{\mathbf{l}}{2} \right)}{\left|\mathbf{r} - \left( \mathbf{r}_0 - \frac{\mathbf{l}}{2} \right)\right|^3} + \frac{q}{4 \pi \varepsilon_0} \frac{\mathbf{r} - \left( \mathbf{r}_0 + \frac{\mathbf{l}}{2} \right)}{\left|\mathbf{r} - \left( \mathbf{r}_0 + \frac{\mathbf{l}}{2} \right)\right|^3} \ .$$

Using the formula for the derivative of the terms

$$\partial_{\ell_k} \frac{x_i \pm \frac{\ell_i}{2}}{\left|\mathbf{x} \pm \frac{\mathbf{l}}{2} \right|^3} = \frac{1}{2} \left[ \pm \frac{\delta_{ik}}{r^3} - 3 r^{-4} \left( \pm \frac{x_k \pm \frac{\ell_k}{2}}{r} \right) \right]$$

$$\left. \partial_{\ell_k} \frac{x_i \pm \frac{\ell_i}{2}}{\left|\mathbf{x} \pm \frac{\mathbf{l}}{2} \right|^3} \right|_{\mathbf{l} = \mathbf{0}} = \mp \frac{1}{2} \left[ - \frac{\delta_{ik}}{|\mathbf{x}|^3} + 3 \left( \frac{x_k}{r^5} \right) \right] = \mp \frac{1}{2} \partial_{r_{0 k}} \frac{r_i - r_{0 i}}{|\mathbf{r} - \mathbf{r}_0|^3} = \mp \frac{1}{2} \nabla_{\mathbf{r}_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} $$

we derive the first-order approximation in $\mathbf{l}$ of the two terms

$$\begin{aligned}
  \frac{\mathbf{r} - \left( \mathbf{r}_0 \mp \frac{\mathbf{l}}{2} \right)}{\left|\mathbf{r} - \left( \mathbf{r}_0 \mp \frac{\mathbf{l}}{2} \right)\right|^3}
  & = \frac{\mathbf{r} - \mathbf{r}_0 }{\left|\mathbf{r} - \mathbf{r}_0 \right|^3} \pm \mathbf{l} \cdot \frac{1}{2} \nabla_{\mathbf{r}_0} \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) + o(|\mathbf{l}|)\\
\end{aligned}$$

and, defining the dipole intensity $\mathbf{P}_0 := q \mathbf{l}$ and taking the quantities to the desired limit, that of the electric field

$$\begin{aligned}
  \mathbf{e}(\mathbf{r})
  & = - \frac{1}{4\pi \varepsilon_0} \, \mathbf{P}_0 \cdot \nabla_{\mathbf{r}_0}  \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right)   = \\
  & = - \frac{1}{4\pi \varepsilon_0} \left[ \frac{(\mathbf{r}-\mathbf{r}_0)(\mathbf{r}-\mathbf{r}_0)}{|\mathbf{r}-\mathbf{r}_0|^5} \cdot \mathbf{P}_0 - \frac{\mathbf{P}_0}{|\mathbf{r}-\mathbf{r}_0|^3} \right] = \\
  & = - \frac{1}{4\pi \varepsilon_0} \left[ \frac{(\mathbf{r}-\mathbf{r}_0) \otimes (\mathbf{r}-\mathbf{r}_0)}{|\mathbf{r}-\mathbf{r}_0|^5} - \frac{\mathbb{I}}{|\mathbf{r}-\mathbf{r}_0|^3} \right] \cdot \mathbf{P}_0 \ .
\end{aligned}$$

**todo** In the general case, it would be necessary to pay attention to the order of the factors in the product between vectors and tensors, but in this case, the symmetry of the second-order tensor (or of the operations) can be exploited.

### Continuous Distribution of Dipoles

A distribution of dipoles with volume density $\mathbf{p}(\mathbf{r_0})$, which produces the elementary dipole $\Delta \mathbf{P}(\mathbf{r}_0) = \mathbf{p}(\mathbf{r}_0) dV_0$ in the volume $d V_0$, produces the electric field

$$\mathbf{e}(\mathbf{r}) = \int_{\mathbf{r}_0 \in V_0} \frac{1}{4 \pi \varepsilon_0} \mathbf{p}(\mathbf{r}_0) \cdot \nabla_{\mathbf{r}_0}  \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) \ , $$

whose expression can be rewritten using the rules of integration by parts

$$\begin{aligned}
\mathbf{e}(\mathbf{r})
  & = \int_{\mathbf{r}_0 \in V_0} \frac{1}{4 \pi \varepsilon_0} \mathbf{p}(\mathbf{r}_0) \cdot \nabla_{\mathbf{r}_0}  \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) = \\
  & = \oint_{\mathbf{r}_0 \in \partial V_0} \frac{1}{4 \pi \varepsilon_0}  \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \underbrace{ \hat{\mathbf{n}}(\mathbf{r}_0) \cdot \mathbf{p}(\mathbf{r}_0) }_{ =: \sigma_P(\mathbf{r}_0)}  + \int_{\mathbf{r}_0 \in V_0} \frac{1}{4 \pi \varepsilon_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \underbrace{ \left( - \nabla_{\mathbf{r}_0} \cdot \mathbf{p}(\mathbf{r}_0) \right)}_{ =: \rho_P(\mathbf{r}_0) } \ , \\
\end{aligned}$$

having defined the surface polarization charge density $\sigma_P$ and the volume polarization charge density $\rho_P$ as the intensities of the distributed sources of the electric field, in analogy with the expression of Coulomb's law.

### Reformulation of Maxwell's Equations and Charge Continuity

Gauss's equation determines the volume flux density of the electric field $\mathbf{e}$,

$$\nabla \cdot \mathbf{e} = \frac{\rho}{\varepsilon_0} \ .$$

By decomposing the charge density as the sum of **free charges** $\rho_f$ and **polarization charges** $\rho_P := - \nabla \cdot \mathbf{p}$, we can rework Gauss's equation,

$$\begin{aligned}
 & \nabla \cdot \mathbf{e} = \frac{\rho_f + \rho_P}{\varepsilon_0} \\
 & \nabla \cdot \left( \varepsilon_0 \mathbf{e} + \mathbf{p} \right) = \rho_f \\ \\
 & \nabla \cdot \mathbf{d} = \rho_f \ ,
\end{aligned}$$

having introduced the **displacement field**, $\mathbf{d} := \varepsilon_0 \mathbf{e} + \mathbf{p}$.

The decomposition of the electric current as the sum $\mathbf{j} = \mathbf{j}_f + \mathbf{j}_P$ of the free current $\mathbf{j}_f$ and the polarization current $\mathbf{j}_P$, allows us to rework the continuity equation of electric charge

$$\begin{aligned}
  0 & = \partial_t \rho + \nabla \cdot \mathbf{j} = \\
    & = \partial_t (\rho_f + \rho_P) + \nabla \cdot \left( \mathbf{j}_f + \mathbf{j}_P \right) = \\
    & = \partial_t \rho_f + \nabla \cdot  \mathbf{j}_f + \partial_t \rho_P + \nabla \cdot \mathbf{j}_P \ ,
\end{aligned}$$

and write the continuity equations for the two charge distributions (of different nature, it is assumed that both must satisfy charge continuity independently, if free charges remain free and polarization charges remain polarization charges),

$$\begin{aligned}
  & \partial_t \rho_f + \nabla \cdot \mathbf{j}_f = 0 \\
  & \partial_t \rho_P + \nabla \cdot \mathbf{j}_P = 0 \qquad \rightarrow \qquad 0 = \nabla \cdot (-\partial_t \mathbf{p} + \mathbf{j}_P) \qquad \rightarrow \qquad \mathbf{j}_P = \partial_t \mathbf{p}
\end{aligned}$$

**todo** *justify absence of constant field*

## Magnetization

### Single Magnetic Moment (Limit of an Elementary Loop)
Using the Biot-Savart law, specialized for a conductor carrying current $i(\mathbf{r}_0)$

$$\begin{aligned}
  d \mathbf{b}(\mathbf{r})
  & = - \frac{\mu}{4 \pi} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \mathbf{j}(\mathbf{r}_0) d V_0 = \\
  & = - \frac{\mu}{4 \pi} i(\mathbf{r}_0) \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \hat{\mathbf{t}}(\mathbf{r}_0) d \ell_0 \ ,
\end{aligned}$$

we can calculate the magnetic field generated by a loop with path $\ell_0 = \partial S_0$ using the PSCE

$$\begin{aligned}
  \mathbf{b}(\mathbf{r})
  & = \oint_{\ell_0} d \mathbf{b}(\mathbf{r}_0) = \\
  & = - \frac{\mu}{4 \pi} i_0 \oint_{\mathbf{r}_0 \in \ell_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \hat{\mathbf{t}}(\mathbf{r}_0)  = \\
  & =   \frac{\mu}{4 \pi} i_0 \int_{\mathbf{r}_0 \in S_0} \hat{\mathbf{n}}(\mathbf{r}_0) \cdot \nabla_{\mathbf{r}_0} \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right)
\end{aligned}$$

The field generated by an elementary loop of surface $S_0$ with normal $\hat{\mathbf{n}}_0$, using the mean value theorem, is

$$\mathbf{b}(\mathbf{r}) = \frac{\mu}{4 \pi} i_0 S_0 \hat{\mathbf{n}}_0 \cdot \nabla_{\mathbf{r}_0} \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) + o(S_0)$$

and as $i_0 \rightarrow \infty$, $S_0 \rightarrow 0$ such that $\mathbf{M}_0 := i_0 S_0 \hat{\mathbf{n}}_0$

$$\begin{aligned}
 \mathbf{b}(\mathbf{r})
  & = \frac{\mu}{4 \pi} \mathbf{M}_0 \cdot \nabla_{\mathbf{r}_0} \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) \\
  & = - \frac{\mu_0}{4\pi} \left[ \frac{(\mathbf{r}-\mathbf{r}_0)(\mathbf{r}-\mathbf{r}_0)}{|\mathbf{r}-\mathbf{r}_0|^5} \cdot \mathbf{M}_0 - \frac{\mathbf{M}_0}{|\mathbf{r}-\mathbf{r}_0|^3} \right] = \\
  & = - \frac{\mu_0}{4\pi} \left[ \frac{(\mathbf{r}-\mathbf{r}_0) \otimes (\mathbf{r}-\mathbf{r}_0)}{|\mathbf{r}-\mathbf{r}_0|^5} - \frac{\mathbb{I}}{|\mathbf{r}-\mathbf{r}_0|^3} \right] \cdot \mathbf{M}_0 \ .
\end{aligned}$$

**todo** Analogy with the electric field produced by a distribution of dipoles.

```{dropdown} Details
$$\oint_{\partial S} A \, t_i = \int_S \varepsilon_{ijk} \, n_j \, \partial_k A
\qquad , \qquad
  \oint_{\partial S} A \, \hat{\mathbf{t}} = \int_S \hat{\mathbf{n}} \times \nabla A$$

$$\begin{aligned}
\oint_{\mathbf{r}_0 \in \ell_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \hat{\mathbf{t}}(\mathbf{r}_0) d \ell_0
  & = \oint_{\mathbf{r}_0 \in \ell_0} \varepsilon_{ijk} \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3}  t_k = \\
  & = \int_{\mathbf{r}_0 \in S_0} \varepsilon_{krs} n_r \partial^0_s \left( \varepsilon_{ijk} \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3} \right) = \\
  & = \int_{\mathbf{r}_0 \in S_0} \left( \delta_{ir} \delta_{js} - \delta_{is} \delta_{jr} \right) n_r \partial^0_s \left( \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3} \right) = \\
  & = \int_{\mathbf{r}_0 \in S_0} \left\{ n_i \underbrace{\partial^0_j \left( \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3} \right)}_{=0} - n_j \partial^0_i \left( \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3} \right) \right\} = \\
  & = - \int_{\mathbf{r}_0 \in S_0} n_j \partial^0_i \left( \frac{r_j - r_{0,j}}{|\mathbf{r} - \mathbf{r}_0|^3} \right) \ .
\end{aligned}$$
```

### Continuous Distribution of Magnetic Moment

To calculate the magnetic field generated by a volume distribution of magnetic moment, we can proceed in analogy with what was done to calculate the electric field generated by a distribution of dipoles

$$\begin{aligned}
\mathbf{b}(\mathbf{r})
  & = \int_{\mathbf{r}_0 \in V_0} \frac{\mu_0}{4 \pi } \mathbf{m}(\mathbf{r}_0) \cdot \nabla_{\mathbf{r}_0}  \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) = \\
  & = \oint_{\mathbf{r}_0 \in \partial V_0} \frac{\mu_0}{4 \pi}  \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \hat{\mathbf{n}}(\mathbf{r}_0) \cdot \mathbf{m}(\mathbf{r}_0) + \int_{\mathbf{r}_0 \in V_0} \frac{\mu_0}{4 \pi} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \,\left( - \nabla_{\mathbf{r}_0} \cdot \mathbf{m}(\mathbf{r}_0) \right) \ , \\
\end{aligned}$$

but without obtaining an analogy with the expression of the Biot-Savart law, which involves the cross product between the term $\frac{\mathbf{r}- \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3}$ and a current density $\mathbf{j}(\mathbf{r}_0)$.

```{dropdown} Details

We can rewrite

$$\begin{aligned}
  \oint_{\mathbf{r}_0 \in \partial V_0} & \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \left( \hat{\mathbf{n}}(\mathbf{r}_0) \times \mathbf{m}(\mathbf{r}_0) \right) \\
  & = \oint_{\mathbf{r}_0 \in \partial V_0} \varepsilon_{ijk} \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} \varepsilon_{krs} n_r m_s = \\
  & = \int_{\mathbf{r}_0 \in V_0} \left( \delta_{ir} \delta_{js} - \delta_{is} \delta_{jr} \right) \partial^0_r \left( \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} m_s \right) = \\
  & = \int_{\mathbf{r}_0 \in V_0} \left\{ \partial^0_i \left( \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} m_j \right) - \partial^0_j \left( \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} m_i \right)  \right\} = \\
  & = \int_{\mathbf{r}_0 \in V_0}
  \left\{ \partial^0_i \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} m_j
         + \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} \partial^0_i m_j
         - \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} \partial^0_j m_i
         - \underbrace{ \partial^0_j \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3}}_{=0} m_i
  \right\} = \\
  & = \int_{\mathbf{r}_0 \in V_0}
  \left\{ \partial^0_i \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} m_j
         + \varepsilon_{ijk} \varepsilon_{krs} \frac{r_j - r_{0,j}}{|\mathbf{r}-\mathbf{r}_0|^3} \partial^0_r m_s
  \right\} = \\
  & = \int_{\mathbf{r}_0 \in V_0}
  \left\{ \nabla_{\mathbf{r}_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r}-\mathbf{r}_0|^3} \cdot \mathbf{m}(\mathbf{r}_0)
         + \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r}-\mathbf{r}_0|^3} \times \left( \nabla_{\mathbf{r}_0} \times \mathbf{m}(\mathbf{r}_0) \right)
  \right\} = \\
\end{aligned}$$

using vector calculus identities,

$$\begin{aligned}
  \mathbf{a} \times (\mathbf{b} \times \mathbf{c}) & = \varepsilon_{ijk} a_j \varepsilon_{krs} b_r c_s = \\
  & = (\delta_{ir} \delta_{js} - \delta_{is} \delta_{jr}) a_j b_r c_s = \\
  & = a_j b_i c_j - c_i b_j a_j = \mathbf{b}(\mathbf{a} \cdot \mathbf{c}) - \mathbf{c} (\mathbf{a} \cdot \mathbf{b})
\end{aligned}$$

$$\begin{aligned}
 a_j \partial_i m_j - a_j \partial_j m_i
 & = (\delta_{ir} \delta_{js} - \delta_{is} \delta_{jr}) a_j \partial_r m_s = \\
 & = \varepsilon_{ijk} \varepsilon_{krs} a_j \partial_r m_s = \\
 & = \mathbf{a} \times \left( \nabla \times \mathbf{m} \right)
\end{aligned}$$

The magnetic field generated by a distribution of magnetic moment can therefore be rewritten as

$$\begin{aligned}
\mathbf{b}(\mathbf{r})
  & = \int_{\mathbf{r}_0 \in V_0} \frac{\mu_0}{4 \pi } \mathbf{m}(\mathbf{r}_0) \cdot \nabla_{\mathbf{r}_0}  \left( \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \right) = \\
  & = - \frac{\mu_0}{4\pi} \oint_{\mathbf{r}_0 \in \partial V_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r} - \mathbf{r}_0|^3} \times \underbrace{ \left( - \hat{\mathbf{n}}(\mathbf{r}_0) \times \mathbf{m}(\mathbf{r}_0) \right) }_{\mathbf{j}^s_M}
  - \frac{\mu_0}{4 \pi} \int_{\mathbf{r}_0 \in V_0} \frac{\mathbf{r} - \mathbf{r}_0}{|\mathbf{r}-\mathbf{r}_0|^3} \times \underbrace{ \left(\nabla_{\mathbf{r}_0} \times \mathbf{m}(\mathbf{r}_0) \right)}_{\mathbf{j}_M} \ ,
\end{aligned}$$

having defined the surface magnetization current density $\mathbf{j}^s_M$ and the volume magnetization current density $\mathbf{j}_M$ as the intensities of the distributed singularities, in analogy with the expression of the Biot-Savart law.

```

### Reformulation of Maxwell's Equations and Charge Continuity

The Ampère-Maxwell law can be rewritten

$$\begin{aligned}
 & \nabla \times \mathbf{b} - \mu_0 \varepsilon_0 \partial_t \mathbf{e} = \mu_0 \mathbf{j} \\
 & \nabla \times \mathbf{b} - \mu_0 \partial_t \left( \mathbf{d} - \mathbf{p} \right) = \mu_0 \left( \mathbf{j}_f + \mathbf{j}_P + \mathbf{j}_M \right) \\
 & \nabla \times \underbrace{\left( \mathbf{b} - \mu_0 \mathbf{m} \right)}_{=: \mu_0 \mathbf{h}} - \mu_0 \partial_t \mathbf{d} + \mu_0 \underbrace{\left( \partial_t \mathbf{p} - \mathbf{j}_P \right)}_{= \mathbf{0}} = \mu_0 \mathbf{j}_f  \\ \\
 & \nabla \times \mathbf{h} - \partial_t \mathbf{d} = \mathbf{j}_f
\end{aligned}$$

From the continuity equation of electric current,

$$\partial_t \rho + \nabla \cdot \mathbf{j} = 0 \ ,$$

we derive the continuity equation for magnetization charges

$$\begin{aligned}
  0 & = \partial_t \rho_M + \nabla \cdot \mathbf{j}_M = \\
    & = \partial_t \rho_M + \underbrace{ \nabla \cdot \nabla \times \mathbf{m}}_{ \equiv \mathbf{0} } \ .
\end{aligned}$$

## Examples
- conductors
- ferromagnetic and weak magnetism (para-, dia-, anti-)

(classical-electromagnetism:media:jump)=
## Jump Conditions
Differential form of Maxwell's equations

$$\begin{cases}
 \nabla \cdot \mathbf{d} = \rho_f \\
 \nabla \times \mathbf{e} + \partial_t \mathbf{b} = \mathbf{0} \\
 \nabla \cdot \mathbf{b} = 0 \\
 \nabla \times \mathbf{h} - \partial_t \mathbf{d} = \mathbf{j}_f
\end{cases}$$

Integral form of Maxwell's equations

$$\begin{cases}
 \displaystyle \oint_{\partial V} \mathbf{d} \cdot \hat{\mathbf{n}} = \int_{V} \rho_f \\
 \displaystyle \oint_{\partial S} \mathbf{e} \cdot \hat{\mathbf{t}} + \dfrac{d}{dt} \int_S \mathbf{b} \cdot \hat{\mathbf{n}} = 0 \\
 \displaystyle \oint_{\partial V} \mathbf{b} \cdot \hat{\mathbf{n}} = 0 \\
 \displaystyle \oint_{\partial S} \mathbf{h} \cdot \hat{\mathbf{t}} - \dfrac{d}{dt} \int_S \mathbf{d} \cdot \hat{\mathbf{n}} = \int_{S} \mathbf{j}_f \cdot \hat{\mathbf{n}} \\
\end{cases}$$

Letting $V$ and $S$ "collapse on a discontinuity"...

$$\begin{cases}
  [ d_n ] = \sigma_f \\
  [ e_t ] = 0 \\
  [ b_n ] = 0 \\
  [ h_t ] = \iota_f \ ,
\end{cases}$$ (eq:em-jump)

being $\sigma_f$ and $\iota_f$ surface charge and current density, with physical dimension $\frac{\text{charge}}{\text{surface}}$, and $\frac{\text{current}}{\text{surface}}$ respectively. These contributions can be thought of as Dirac delta contributions in volume density, namely

$$\rho(\mathbf{r},t) = \rho_0(\mathbf{r},t) + \sigma(\mathbf{r}_s,t) \delta_{1}(\mathbf{r}-\mathbf{r}_s) \ ,$$

being $\rho(\mathbf{r},t)$ the regular part of the volume density in all the points of the domain $\mathbf{r} \in V$, $\sigma(\mathbf{r}_s,t)$ the surface density on 2-dimensional surfaces $\mathbf{r}_s \in S$, $\delta_1()$ the Dirac's delta with physical dimension $\frac{1}{\text{length}}$.

If there's no free surface charge and currents, jump conditions for linear media become

$$\begin{cases}
  [ d_n ] = 0 \\
  [ e_t ] = 0 \\
  [ b_n ] = 0 \\
  [ h_t ] = 0 \ ,
\end{cases}
\qquad \rightarrow \qquad
\begin{cases}
  d_{n,1} = d_{n,2}  \quad \rightarrow \quad \varepsilon_1 e_{n,1} = \varepsilon_2 e_{n,2} \\
  e_{t,1} = e_{t,2}  \\
  b_{n,1} = b_{n,2}  \\
  h_{t,1} = h_{t,2}  \quad \rightarrow \quad \frac{1}{\mu_1} b_{t,1} = \frac{1}{\mu_2} b_{t,2} \\
\end{cases}
$$ (eq:em-jump:no-surf-density)

